REACT_APP_FIREBASE_API_KEY=AIzaSyCLzmv236TAOdRI6CvsVJOGVW8tCDtzh7k
REACT_APP_FIREBASE_AUTH_DOMAIN=pizza-maker-dev.firebaseapp.com
REACT_APP_FIREBASE_PROJECT_ID=pizza-maker-dev
REACT_APP_FIREBASE_STORAGE_BUCKET=pizza-maker-dev.appspot.com
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=896552077837
REACT_APP_FIREBASE_APP_ID=1:896552077837:web:a55261a674858cb467e344
REACT_APP_FIREBASE_MEASUREMENT_ID=G-CD7C24EEVR