apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pizzamaker.fullname" . }}-config
  labels:
    {{- include "pizzamaker.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  DATABASE_USERNAME: {{ .Values.config.databaseUsername | quote }}
  ALLOWED_ORIGINS: {{ .Values.config.allowedOrigins | quote }}

  KAFKA_ENABLED: {{ .Values.kafka.enabled | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}

  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"