CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid         VARCHAR(36)  NOT NULL UNIQUE,
    first_name  VARCHAR(100) NOT NULL,
    email_id    VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    user_type   VARCHAR(20)  NOT NULL,
    role        VARCHAR(30)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);
