ALTER TABLE orders DROP COLUMN provolone;
ALTER TABLE orders ADD COLUMN cheddar BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN parmesan_asiago BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN ricotta BOOLEAN NOT NULL DEFAULT FALSE;
