-- An order stores only its current status; this table records every transition
-- so the kitchen and the customer get an auditable timeline (when it was
-- confirmed, when it went into the oven, when it went out for delivery) rather
-- than a single mutable field with no history.
CREATE TABLE order_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT       NOT NULL REFERENCES orders(id),
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    changed_by  VARCHAR(255),
    changed_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_status_history_order ON order_status_history (order_id);
