-- Priced breakdown of an order, snapshotted at order time. The order's total is
-- stored on orders.price, but the line items record HOW that total was reached
-- (base size, sauce, each cheese, each topping, delivery fee). Because it's a
-- snapshot, a later catalog/pricing change never rewrites a historical receipt,
-- and it doubles as the source for analytics (e.g. popular toppings) so we don't
-- have to parse the JSON toppings blob in SQL.
CREATE TABLE order_line_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL REFERENCES orders(id),
    line_type  VARCHAR(20)   NOT NULL,
    ref_id     VARCHAR(50),
    label      VARCHAR(100)  NOT NULL,
    amount     NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP     NOT NULL
);

CREATE INDEX idx_line_item_order ON order_line_item (order_id);
-- Analytics group by line_type + ref_id (e.g. "how often is pepperoni ordered").
CREATE INDEX idx_line_item_type_ref ON order_line_item (line_type, ref_id);
