-- Promote the kitchen's topping allow-list out of a hardcoded Java Set
-- (the old ToppingCatalog.IDS) into a real table, so toppings can be enabled or
-- retired without a redeploy and the order validator reads its allow-list from
-- the database. Codes match the frontend topping art ids exactly.
CREATE TABLE topping (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code     VARCHAR(50)  NOT NULL UNIQUE,
    name     VARCHAR(100) NOT NULL,
    category VARCHAR(30)  NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO topping (code, name, category, active) VALUES
    ('pepperoni', 'Pepperoni', 'MEAT',   TRUE),
    ('sausage',   'Sausage',   'MEAT',   TRUE),
    ('bacon',     'Bacon',     'MEAT',   TRUE),
    ('chicken',   'Chicken',   'MEAT',   TRUE),
    ('peppers',   'Peppers',   'VEGGIE', TRUE),
    ('olives',    'Olives',    'VEGGIE', TRUE),
    ('jalapeno',  'Jalapeno',  'VEGGIE', TRUE),
    ('mushroom',  'Mushroom',  'VEGGIE', TRUE),
    ('onion',     'Onion',     'VEGGIE', TRUE),
    ('spinach',   'Spinach',   'VEGGIE', TRUE),
    ('tomato',    'Tomato',    'VEGGIE', TRUE),
    ('zucchini',  'Zucchini',  'VEGGIE', TRUE),
    ('broccoli',  'Broccoli',  'VEGGIE', TRUE),
    ('corn',      'Corn',      'VEGGIE', TRUE);

-- Server-owned preset catalogue. The frontend currently hardcodes its presets;
-- this table is the backend source of truth a future build can fetch from, so
-- the menu lives in one place instead of being duplicated in the client.
-- toppings reuses the same JSON {id,quantity} shape as orders.toppings.
CREATE TABLE pizza_preset (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)   NOT NULL UNIQUE,
    name        VARCHAR(100)  NOT NULL,
    description VARCHAR(255),
    pizza_size  VARCHAR(5)    NOT NULL,
    sauce_type  VARCHAR(20)   NOT NULL DEFAULT 'ROBUST_TOMATO',
    crust_style VARCHAR(20)   NOT NULL DEFAULT 'HAND_TOSSED',
    toppings    VARCHAR(2000) NOT NULL DEFAULT '[]',
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    sort_order  INT           NOT NULL DEFAULT 0
);

INSERT INTO pizza_preset (code, name, description, pizza_size, sauce_type, crust_style, toppings, active, sort_order) VALUES
    ('margherita', 'Margherita', 'Classic tomato, mozzarella and basil', 'M', 'ROBUST_TOMATO', 'HAND_TOSSED',
        '[{"id":"tomato","quantity":"REGULAR"}]', TRUE, 1),
    ('pepperoni', 'Pepperoni Feast', 'Loaded with extra pepperoni', 'L', 'ROBUST_TOMATO', 'HAND_TOSSED',
        '[{"id":"pepperoni","quantity":"EXTRA"}]', TRUE, 2),
    ('meat_lovers', 'Meat Lovers', 'Pepperoni, sausage, bacon and chicken', 'L', 'ROBUST_TOMATO', 'HAND_TOSSED',
        '[{"id":"pepperoni","quantity":"REGULAR"},{"id":"sausage","quantity":"REGULAR"},{"id":"bacon","quantity":"REGULAR"},{"id":"chicken","quantity":"REGULAR"}]', TRUE, 3),
    ('veggie', 'Garden Veggie', 'Peppers, onion, mushroom, olives and spinach', 'M', 'ROBUST_TOMATO', 'HAND_TOSSED',
        '[{"id":"peppers","quantity":"REGULAR"},{"id":"onion","quantity":"REGULAR"},{"id":"mushroom","quantity":"REGULAR"},{"id":"olives","quantity":"REGULAR"},{"id":"spinach","quantity":"REGULAR"}]', TRUE, 4),
    ('bbq_chicken', 'BBQ Chicken', 'Grilled chicken on a BBQ base with onion', 'M', 'BBQ', 'HAND_TOSSED',
        '[{"id":"chicken","quantity":"EXTRA"},{"id":"onion","quantity":"LIGHT"}]', TRUE, 5);
