-- Transactional outbox. Order side effects (confirmation, real-time status
-- push) are written here in the SAME transaction as the order change, then
-- delivered asynchronously by a polling relay (OutboxRelay). This is crash-safe:
-- if the process dies after commit but before delivery, the row is still PENDING
-- and gets retried, so a committed order can never silently lose its side effect.
CREATE TABLE outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(30)   NOT NULL,
    aggregate_id    VARCHAR(36)   NOT NULL,
    event_type      VARCHAR(40)   NOT NULL,
    payload         VARCHAR(2000) NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    attempts        INT           NOT NULL DEFAULT 0,
    created_at      TIMESTAMP     NOT NULL,
    next_attempt_at TIMESTAMP     NOT NULL,
    processed_at    TIMESTAMP
);

-- The relay polls for PENDING rows that are due (next_attempt_at <= now).
CREATE INDEX idx_outbox_dispatch ON outbox_event (status, next_attempt_at);
