-- Payment intent per order, modelled on the Stripe PaymentIntent lifecycle so a
-- real Stripe adapter is a drop-in. intent_id is unique (and the idempotency
-- anchor for webhook replays); the provider column keeps it provider-agnostic.
CREATE TABLE payment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL REFERENCES orders(id),
    provider   VARCHAR(30)   NOT NULL,
    intent_id  VARCHAR(100)  NOT NULL UNIQUE,
    amount     NUMERIC(10,2) NOT NULL,
    currency   VARCHAR(3)    NOT NULL DEFAULT 'USD',
    status     VARCHAR(20)   NOT NULL DEFAULT 'REQUIRES_PAYMENT',
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP     NOT NULL
);

CREATE INDEX idx_payment_order ON payment (order_id);
